typedef enum {
	CURLE_OK = 0,
	CURLE_UNSUPPORTED_PROTOCOL,    /* 1 */
	CURLE_FAILED_INIT,             /* 2 */
	CURLE_URL_MALFORMAT,           /* 3 */
	CURLE_NOT_BUILT_IN,            /* 4 - [was obsoleted in August 2007 for
																		7.17.0, reused in April 2011 for 7.21.5] */
	CURLE_COULDNT_RESOLVE_PROXY,   /* 5 */
	CURLE_COULDNT_RESOLVE_HOST,    /* 6 */
	CURLE_COULDNT_CONNECT,         /* 7 */
	CURLE_WEIRD_SERVER_REPLY,      /* 8 */
	CURLE_REMOTE_ACCESS_DENIED,    /* 9 a service was denied by the server
																		due to lack of access - when login fails
																		this is not returned. */
	CURLE_FTP_ACCEPT_FAILED,       /* 10 - [was obsoleted in April 2006 for
																		7.15.4, reused in Dec 2011 for 7.24.0]*/
	CURLE_FTP_WEIRD_PASS_REPLY,    /* 11 */
	CURLE_FTP_ACCEPT_TIMEOUT,      /* 12 - timeout occurred accepting server
																		[was obsoleted in August 2007 for 7.17.0,
																		reused in Dec 2011 for 7.24.0]*/
	CURLE_FTP_WEIRD_PASV_REPLY,    /* 13 */
	CURLE_FTP_WEIRD_227_FORMAT,    /* 14 */
	CURLE_FTP_CANT_GET_HOST,       /* 15 */
	CURLE_HTTP2,                   /* 16 - A problem in the http2 framing layer.
																		[was obsoleted in August 2007 for 7.17.0,
																		reused in July 2014 for 7.38.0] */
	CURLE_FTP_COULDNT_SET_TYPE,    /* 17 */
	CURLE_PARTIAL_FILE,            /* 18 */
	CURLE_FTP_COULDNT_RETR_FILE,   /* 19 */
	CURLE_OBSOLETE20,              /* 20 - NOT USED */
	CURLE_QUOTE_ERROR,             /* 21 - quote command failure */
	CURLE_HTTP_RETURNED_ERROR,     /* 22 */
	CURLE_WRITE_ERROR,             /* 23 */
	CURLE_OBSOLETE24,              /* 24 - NOT USED */
	CURLE_UPLOAD_FAILED,           /* 25 - failed upload "command" */
	CURLE_READ_ERROR,              /* 26 - couldn"t open/read from file */
	CURLE_OUT_OF_MEMORY,           /* 27 */
	/* Note: CURLE_OUT_OF_MEMORY may sometimes indicate a conversion error
					 instead of a memory allocation error if CURL_DOES_CONVERSIONS
					 is defined
	*/
	CURLE_OPERATION_TIMEDOUT,      /* 28 - the timeout time was reached */
	CURLE_OBSOLETE29,              /* 29 - NOT USED */
	CURLE_FTP_PORT_FAILED,         /* 30 - FTP PORT operation failed */
	CURLE_FTP_COULDNT_USE_REST,    /* 31 - the REST command failed */
	CURLE_OBSOLETE32,              /* 32 - NOT USED */
	CURLE_RANGE_ERROR,             /* 33 - RANGE "command" didn"t work */
	CURLE_HTTP_POST_ERROR,         /* 34 */
	CURLE_SSL_CONNECT_ERROR,       /* 35 - wrong when connecting with SSL */
	CURLE_BAD_DOWNLOAD_RESUME,     /* 36 - couldn"t resume download */
	CURLE_FILE_COULDNT_READ_FILE,  /* 37 */
	CURLE_LDAP_CANNOT_BIND,        /* 38 */
	CURLE_LDAP_SEARCH_FAILED,      /* 39 */
	CURLE_OBSOLETE40,              /* 40 - NOT USED */
	CURLE_FUNCTION_NOT_FOUND,      /* 41 - NOT USED starting with 7.53.0 */
	CURLE_ABORTED_BY_CALLBACK,     /* 42 */
	CURLE_BAD_FUNCTION_ARGUMENT,   /* 43 */
	CURLE_OBSOLETE44,              /* 44 - NOT USED */
	CURLE_INTERFACE_FAILED,        /* 45 - CURLOPT_INTERFACE failed */
	CURLE_OBSOLETE46,              /* 46 - NOT USED */
	CURLE_TOO_MANY_REDIRECTS,      /* 47 - catch endless re-direct loops */
	CURLE_UNKNOWN_OPTION,          /* 48 - User specified an unknown option */
	CURLE_TELNET_OPTION_SYNTAX,    /* 49 - Malformed telnet option */
	CURLE_OBSOLETE50,              /* 50 - NOT USED */
	CURLE_OBSOLETE51,              /* 51 - NOT USED */
	CURLE_GOT_NOTHING,             /* 52 - when this is a specific error */
	CURLE_SSL_ENGINE_NOTFOUND,     /* 53 - SSL crypto engine not found */
	CURLE_SSL_ENGINE_SETFAILED,    /* 54 - can not set SSL crypto engine as
																		default */
	CURLE_SEND_ERROR,              /* 55 - failed sending network data */
	CURLE_RECV_ERROR,              /* 56 - failure in receiving network data */
	CURLE_OBSOLETE57,              /* 57 - NOT IN USE */
	CURLE_SSL_CERTPROBLEM,         /* 58 - problem with the local certificate */
	CURLE_SSL_CIPHER,              /* 59 - couldn"t use specified cipher */
	CURLE_PEER_FAILED_VERIFICATION, /* 60 - peer"s certificate or fingerprint
																		 wasn"t verified fine */
	CURLE_BAD_CONTENT_ENCODING,    /* 61 - Unrecognized/bad encoding */
	CURLE_LDAP_INVALID_URL,        /* 62 - Invalid LDAP URL */
	CURLE_FILESIZE_EXCEEDED,       /* 63 - Maximum file size exceeded */
	CURLE_USE_SSL_FAILED,          /* 64 - Requested FTP SSL level failed */
	CURLE_SEND_FAIL_REWIND,        /* 65 - Sending the data requires a rewind
																		that failed */
	CURLE_SSL_ENGINE_INITFAILED,   /* 66 - failed to initialise ENGINE */
	CURLE_LOGIN_DENIED,            /* 67 - user, password or similar was not
																		accepted and we failed to login */
	CURLE_TFTP_NOTFOUND,           /* 68 - file not found on server */
	CURLE_TFTP_PERM,               /* 69 - permission problem on server */
	CURLE_REMOTE_DISK_FULL,        /* 70 - out of disk space on server */
	CURLE_TFTP_ILLEGAL,            /* 71 - Illegal TFTP operation */
	CURLE_TFTP_UNKNOWNID,          /* 72 - Unknown transfer ID */
	CURLE_REMOTE_FILE_EXISTS,      /* 73 - File already exists */
	CURLE_TFTP_NOSUCHUSER,         /* 74 - No such user */
	CURLE_CONV_FAILED,             /* 75 - conversion failed */
	CURLE_CONV_REQD,               /* 76 - caller must register conversion
																		callbacks using curl_easy_setopt options
																		CURLOPT_CONV_FROM_NETWORK_FUNCTION,
																		CURLOPT_CONV_TO_NETWORK_FUNCTION, and
																		CURLOPT_CONV_FROM_UTF8_FUNCTION */
	CURLE_SSL_CACERT_BADFILE,      /* 77 - could not load CACERT file, missing
																		or wrong format */
	CURLE_REMOTE_FILE_NOT_FOUND,   /* 78 - remote file not found */
	CURLE_SSH,                     /* 79 - error from the SSH layer, somewhat
																		generic so the error message will be of
																		interest when this has happened */

	CURLE_SSL_SHUTDOWN_FAILED,     /* 80 - Failed to shut down the SSL
																		connection */
	CURLE_AGAIN,                   /* 81 - socket is not ready for send/recv,
																		wait till it"s ready and try again (Added
																		in 7.18.2) */
	CURLE_SSL_CRL_BADFILE,         /* 82 - could not load CRL file, missing or
																		wrong format (Added in 7.19.0) */
	CURLE_SSL_ISSUER_ERROR,        /* 83 - Issuer check failed.  (Added in
																		7.19.0) */
	CURLE_FTP_PRET_FAILED,         /* 84 - a PRET command failed */
	CURLE_RTSP_CSEQ_ERROR,         /* 85 - mismatch of RTSP CSeq numbers */
	CURLE_RTSP_SESSION_ERROR,      /* 86 - mismatch of RTSP Session Ids */
	CURLE_FTP_BAD_FILE_LIST,       /* 87 - unable to parse FTP file list */
	CURLE_CHUNK_FAILED,            /* 88 - chunk callback reported error */
	CURLE_NO_CONNECTION_AVAILABLE, /* 89 - No connection available, the
																		session will be queued */
	CURLE_SSL_PINNEDPUBKEYNOTMATCH, /* 90 - specified pinned public key did not
																		 match */
	CURLE_SSL_INVALIDCERTSTATUS,   /* 91 - invalid certificate status */
	CURLE_HTTP2_STREAM,            /* 92 - stream error in HTTP/2 framing layer
																		*/
	CURLE_RECURSIVE_API_CALL,      /* 93 - an api function was called from
																		inside a callback */
	CURLE_AUTH_ERROR,              /* 94 - an authentication function returned an
																		error */
	CURLE_HTTP3,                   /* 95 - An HTTP/3 layer problem */
	CURL_LAST, /* never use! */
	CURL_ZERO_TERMINATED
} CURLcode;

typedef enum {
	CURLOPTTYPE_LONG          = 0,
	CURLOPTTYPE_OBJECTPOINT   = 10000,
	CURLOPTTYPE_FUNCTIONPOINT = 20000,
	CURLOPTTYPE_OFF_T         = 30000
};

typedef enum {
	CURLOPT_SSL_OPTIONS = CURLOPTTYPE_LONG+216,
	CURLOPT_USERNAME = CURLOPTTYPE_OBJECTPOINT+173,
	CURLOPT_FTP_RESPONSE_TIMEOUT = CURLOPTTYPE_LONG+112,
	CURLOPT_OPENSOCKETDATA = CURLOPTTYPE_OBJECTPOINT+164,
	CURLOPT_IOCTLDATA = CURLOPTTYPE_OBJECTPOINT+131,
	CURLOPT_MAX_RECV_SPEED_LARGE = CURLOPTTYPE_OFF_T+146,
	CURLOPT_FTPPORT = CURLOPTTYPE_OBJECTPOINT+17,
	CURLOPT_NOSIGNAL = CURLOPTTYPE_LONG+99,
	CURLOPT_OBSOLETE72 = CURLOPTTYPE_LONG+72,
	CURLOPT_MAX_SEND_SPEED_LARGE = CURLOPTTYPE_OFF_T+145,
	CURLOPT_COOKIE = CURLOPTTYPE_OBJECTPOINT+22,
	CURLOPT_FNMATCH_DATA = CURLOPTTYPE_OBJECTPOINT+202,
	CURLOPT_APPEND = CURLOPTTYPE_LONG+50,
	CURLOPT_FTP_FILEMETHOD = CURLOPTTYPE_LONG+138,
	CURLOPT_PUT = CURLOPTTYPE_LONG+54,
	CURLOPT_COOKIELIST = CURLOPTTYPE_OBJECTPOINT+135,
	CURLOPT_SEEKFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+167,
	CURLOPT_SSL_VERIFYHOST = CURLOPTTYPE_LONG+81,
	CURLOPT_SSLCERT = CURLOPTTYPE_OBJECTPOINT+25,
	CURLOPT_FTP_ALTERNATIVE_TO_USER = CURLOPTTYPE_OBJECTPOINT+147,
	CURLOPT_ACCEPTTIMEOUT_MS = CURLOPTTYPE_LONG+212,
	CURLOPT_READDATA = CURLOPTTYPE_OBJECTPOINT+9,
	CURLOPT_TELNETOPTIONS = CURLOPTTYPE_OBJECTPOINT+70,
	CURLOPT_ERRORBUFFER = CURLOPTTYPE_OBJECTPOINT+10,
	CURLOPT_REFERER = CURLOPTTYPE_OBJECTPOINT+16,
	CURLOPT_LOCALPORT = CURLOPTTYPE_LONG+139,
	CURLOPT_FORBID_REUSE = CURLOPTTYPE_LONG+75,
	CURLOPT_SSLCERTTYPE = CURLOPTTYPE_OBJECTPOINT+86,
	CURLOPT_RANGE = CURLOPTTYPE_OBJECTPOINT+7,
	CURLOPT_NETRC = CURLOPTTYPE_LONG+51,
	CURLOPT_SSLKEY = CURLOPTTYPE_OBJECTPOINT+87,
	CURLOPT_FTP_SKIP_PASV_IP = CURLOPTTYPE_LONG+137,
	CURLOPT_CONV_TO_NETWORK_FUNCTION = CURLOPTTYPE_FUNCTIONPOINT+143,
	CURLOPT_TIMEVALUE = CURLOPTTYPE_LONG+34,
	CURLOPT_SOCKS5_GSSAPI_NEC = CURLOPTTYPE_LONG+180,
	CURLOPT_SHARE = CURLOPTTYPE_OBJECTPOINT+100,
	CURLOPT_RTSP_TRANSPORT = CURLOPTTYPE_OBJECTPOINT+192,
	CURLOPT_VERBOSE = CURLOPTTYPE_LONG+41,
	CURLOPT_URL = CURLOPTTYPE_OBJECTPOINT+2,
	CURLOPT_INTERFACE = CURLOPTTYPE_OBJECTPOINT+62,
	CURLOPT_FTPSSLAUTH = CURLOPTTYPE_LONG+129,
	CURLOPT_CRLFILE = CURLOPTTYPE_OBJECTPOINT+169,
	CURLOPT_TRANSFER_ENCODING = CURLOPTTYPE_LONG+207,
	CURLOPT_ACCEPT_ENCODING = CURLOPTTYPE_OBJECTPOINT+102,
	CURLOPT_PREQUOTE = CURLOPTTYPE_OBJECTPOINT+93,
	CURLOPT_TLSAUTH_PASSWORD = CURLOPTTYPE_OBJECTPOINT+205,
	CURLOPT_RESUME_FROM_LARGE = CURLOPTTYPE_OFF_T+116,
	CURLOPT_STREAM_DEPENDS = CURLOPTTYPE_OBJECTPOINT+240,
	CURLOPT_TRANSFERTEXT = CURLOPTTYPE_LONG+53,
	CURLOPT_POST = CURLOPTTYPE_LONG+47,
	CURLOPT_PROXYUSERPWD = CURLOPTTYPE_OBJECTPOINT+6,
	CURLOPT_DEFAULT_PROTOCOL = CURLOPTTYPE_OBJECTPOINT+238,
	CURLOPT_PIPEWAIT = CURLOPTTYPE_LONG+237,
	CURLOPT_FTP_ACCOUNT = CURLOPTTYPE_OBJECTPOINT+134,
	CURLOPT_OBSOLETE40 = CURLOPTTYPE_OBJECTPOINT+40,
	CURLOPT_PROXY_SERVICE_NAME = CURLOPTTYPE_OBJECTPOINT+235,
	CURLOPT_MAXREDIRS = CURLOPTTYPE_LONG+68,
	CURLOPT_SOCKOPTFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+148,
	CURLOPT_PATH_AS_IS = CURLOPTTYPE_LONG+234,
	CURLOPT_FRESH_CONNECT = CURLOPTTYPE_LONG+74,
	CURLOPT_PROGRESSFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+56,
	CURLOPT_SSL_FALSESTART = CURLOPTTYPE_LONG+233,
	CURLOPT_RTSP_STREAM_URI = CURLOPTTYPE_OBJECTPOINT+191,
	CURLOPT_USERAGENT = CURLOPTTYPE_OBJECTPOINT+18,
	CURLOPT_NOBODY = CURLOPTTYPE_LONG+44,
	CURLOPT_DNS_INTERFACE = CURLOPTTYPE_OBJECTPOINT+221,
	CURLOPT_PROGRESSDATA = CURLOPTTYPE_OBJECTPOINT+57,
	CURLOPT_ISSUERCERT = CURLOPTTYPE_OBJECTPOINT+170,
	CURLOPT_SEEKDATA = CURLOPTTYPE_OBJECTPOINT+168,
	CURLOPT_PINNEDPUBLICKEY = CURLOPTTYPE_OBJECTPOINT+230,
	CURLOPT_FTP_USE_EPSV = CURLOPTTYPE_LONG+85,
	CURLOPT_HEADEROPT = CURLOPTTYPE_LONG+229,
	CURLOPT_NOPROXY = CURLOPTTYPE_OBJECTPOINT+177,
	CURLOPT_EXPECT_100_TIMEOUT_MS = CURLOPTTYPE_LONG+227,
	CURLOPT_SSL_ENABLE_ALPN = CURLOPTTYPE_LONG+226,
	CURLOPT_HEADERFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+79,
	CURLOPT_SSL_ENABLE_NPN = CURLOPTTYPE_LONG+225,
	CURLOPT_PORT = CURLOPTTYPE_LONG+3,
	CURLOPT_SSL_CIPHER_LIST = CURLOPTTYPE_OBJECTPOINT+83,
	CURLOPT_MAIL_RCPT = CURLOPTTYPE_OBJECTPOINT+187,
	CURLOPT_DNS_LOCAL_IP4 = CURLOPTTYPE_OBJECTPOINT+222,
	CURLOPT_CHUNK_DATA = CURLOPTTYPE_OBJECTPOINT+201,
	CURLOPT_SSH_AUTH_TYPES = CURLOPTTYPE_LONG+151,
	CURLOPT_DNS_LOCAL_IP6 = CURLOPTTYPE_OBJECTPOINT+223,
	CURLOPT_XFERINFOFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+219,
	CURLOPT_PROXYUSERNAME = CURLOPTTYPE_OBJECTPOINT+175,
	CURLOPT_LOCALPORTRANGE = CURLOPTTYPE_LONG+140,
	CURLOPT_HTTPPOST = CURLOPTTYPE_OBJECTPOINT+24,
	CURLOPT_PROXYAUTH = CURLOPTTYPE_LONG+111,
	CURLOPT_RANDOM_FILE = CURLOPTTYPE_OBJECTPOINT+76,
	CURLOPT_NEW_DIRECTORY_PERMS = CURLOPTTYPE_LONG+160,
	CURLOPT_MAIL_AUTH = CURLOPTTYPE_OBJECTPOINT+217,
	CURLOPT_TCP_KEEPINTVL = CURLOPTTYPE_LONG+215,
	CURLOPT_TCP_KEEPIDLE = CURLOPTTYPE_LONG+214,
	CURLOPT_MAXCONNECTS = CURLOPTTYPE_LONG+71,
	CURLOPT_TCP_KEEPALIVE = CURLOPTTYPE_LONG+213,
	CURLOPT_PRIVATE = CURLOPTTYPE_OBJECTPOINT+103,
	CURLOPT_FTP_USE_EPRT = CURLOPTTYPE_LONG+106,
	CURLOPT_DNS_SERVERS = CURLOPTTYPE_OBJECTPOINT+211,
	CURLOPT_INTERLEAVEFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+196,
	CURLOPT_POSTREDIR = CURLOPTTYPE_LONG+161,
	CURLOPT_SSH_PUBLIC_KEYFILE = CURLOPTTYPE_OBJECTPOINT+152,
	CURLOPT_CLOSESOCKETFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+208,
	CURLOPT_SSH_PRIVATE_KEYFILE = CURLOPTTYPE_OBJECTPOINT+153,
	CURLOPT_OPENSOCKETFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+163,
	CURLOPT_STREAM_DEPENDS_E = CURLOPTTYPE_OBJECTPOINT+241,
	CURLOPT_CERTINFO = CURLOPTTYPE_LONG+172,
	CURLOPT_HTTP200ALIASES = CURLOPTTYPE_OBJECTPOINT+104,
	CURLOPT_MAXFILESIZE = CURLOPTTYPE_LONG+114,
	CURLOPT_COOKIEJAR = CURLOPTTYPE_OBJECTPOINT+82,
	CURLOPT_PROXYPORT = CURLOPTTYPE_LONG+59,
	CURLOPT_RESOLVE = CURLOPTTYPE_OBJECTPOINT+203,
	CURLOPT_FNMATCH_FUNCTION = CURLOPTTYPE_FUNCTIONPOINT+200,
	CURLOPT_SSH_HOST_PUBLIC_KEY_MD5 = CURLOPTTYPE_OBJECTPOINT+162,
	CURLOPT_HEADER = CURLOPTTYPE_LONG+42,
	CURLOPT_NEW_FILE_PERMS = CURLOPTTYPE_LONG+159,
	CURLOPT_DNS_CACHE_TIMEOUT = CURLOPTTYPE_LONG+92,
	CURLOPT_CHUNK_BGN_FUNCTION = CURLOPTTYPE_FUNCTIONPOINT+198,
	CURLOPT_RTSP_REQUEST = CURLOPTTYPE_LONG+189,
	CURLOPT_POSTFIELDSIZE = CURLOPTTYPE_LONG+60,
	CURLOPT_HTTP_TRANSFER_DECODING = CURLOPTTYPE_LONG+157,
	CURLOPT_GSSAPI_DELEGATION = CURLOPTTYPE_LONG+210,
	CURLOPT_CHUNK_END_FUNCTION = CURLOPTTYPE_FUNCTIONPOINT+199,
	CURLOPT_RTSP_SERVER_CSEQ = CURLOPTTYPE_LONG+194,
	CURLOPT_LOW_SPEED_TIME = CURLOPTTYPE_LONG+20,
	CURLOPT_RTSP_SESSION_ID = CURLOPTTYPE_OBJECTPOINT+190,
	CURLOPT_TCP_NODELAY = CURLOPTTYPE_LONG+121,
	CURLOPT_CONNECTTIMEOUT = CURLOPTTYPE_LONG+78,
	CURLOPT_WILDCARDMATCH = CURLOPTTYPE_LONG+197,
	CURLOPT_FTP_USE_PRET = CURLOPTTYPE_LONG+188,
	CURLOPT_XOAUTH2_BEARER = CURLOPTTYPE_OBJECTPOINT+220,
	CURLOPT_NOPROGRESS = CURLOPTTYPE_LONG+43,
	CURLOPT_MAIL_FROM = CURLOPTTYPE_OBJECTPOINT+186,
	CURLOPT_AUTOREFERER = CURLOPTTYPE_LONG+58,
	CURLOPT_POSTFIELDS = CURLOPTTYPE_OBJECTPOINT+15,
	CURLOPT_MAXFILESIZE_LARGE = CURLOPTTYPE_OFF_T+117,
	CURLOPT_FILETIME = CURLOPTTYPE_LONG+69,
	CURLOPT_SSH_KEYDATA = CURLOPTTYPE_OBJECTPOINT+185,
	CURLOPT_SSH_KEYFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+184,
	CURLOPT_SSH_KNOWNHOSTS = CURLOPTTYPE_OBJECTPOINT+183,
	CURLOPT_REDIR_PROTOCOLS = CURLOPTTYPE_LONG+182,
	CURLOPT_USE_SSL = CURLOPTTYPE_LONG+119,
	CURLOPT_HEADERDATA = CURLOPTTYPE_OBJECTPOINT+29,
	CURLOPT_PROTOCOLS = CURLOPTTYPE_LONG+181,
	CURLOPT_SOCKS5_GSSAPI_SERVICE = CURLOPTTYPE_OBJECTPOINT+179,
	CURLOPT_TIMEOUT_MS = CURLOPTTYPE_LONG+155,
	CURLOPT_SSL_VERIFYPEER = CURLOPTTYPE_LONG+64,
	CURLOPT_STDERR = CURLOPTTYPE_OBJECTPOINT+37,
	CURLOPT_PROXYHEADER = CURLOPTTYPE_OBJECTPOINT+228,
	CURLOPT_PROXYPASSWORD = CURLOPTTYPE_OBJECTPOINT+176,
	CURLOPT_STREAM_WEIGHT = CURLOPTTYPE_LONG+239,
	CURLOPT_SSL_CTX_FUNCTION = CURLOPTTYPE_FUNCTIONPOINT+108,
	CURLOPT_TLSAUTH_USERNAME = CURLOPTTYPE_OBJECTPOINT+204,
	CURLOPT_ADDRESS_SCOPE = CURLOPTTYPE_LONG+171,
	CURLOPT_FTP_CREATE_MISSING_DIRS = CURLOPTTYPE_LONG+110,
	CURLOPT_PROXY_TRANSFER_MODE = CURLOPTTYPE_LONG+166,
	CURLOPT_COPYPOSTFIELDS = CURLOPTTYPE_OBJECTPOINT+165,
	CURLOPT_TLSAUTH_TYPE = CURLOPTTYPE_OBJECTPOINT+206,
	CURLOPT_SASL_IR = CURLOPTTYPE_LONG+218,
	CURLOPT_HTTP_CONTENT_DECODING = CURLOPTTYPE_LONG+158,
	CURLOPT_COOKIEFILE = CURLOPTTYPE_OBJECTPOINT+31,
	CURLOPT_TFTP_BLKSIZE = CURLOPTTYPE_LONG+178,
	CURLOPT_FTP_SSL_CCC = CURLOPTTYPE_LONG+154,
	CURLOPT_CLOSESOCKETDATA = CURLOPTTYPE_OBJECTPOINT+209,
	CURLOPT_SSL_SESSIONID_CACHE = CURLOPTTYPE_LONG+150,
	CURLOPT_POSTFIELDSIZE_LARGE = CURLOPTTYPE_OFF_T+120,
	CURLOPT_SOCKOPTDATA = CURLOPTTYPE_OBJECTPOINT+149,
	CURLOPT_FOLLOWLOCATION = CURLOPTTYPE_LONG+52,
	CURLOPT_RESUME_FROM = CURLOPTTYPE_LONG+21,
	CURLOPT_HTTPPROXYTUNNEL = CURLOPTTYPE_LONG+61,
	CURLOPT_DNS_USE_GLOBAL_CACHE = CURLOPTTYPE_LONG+91,
	CURLOPT_LOGIN_OPTIONS = CURLOPTTYPE_OBJECTPOINT+224,
	CURLOPT_CONNECTTIMEOUT_MS = CURLOPTTYPE_LONG+156,
	CURLOPT_COOKIESESSION = CURLOPTTYPE_LONG+96,
	CURLOPT_IPRESOLVE = CURLOPTTYPE_LONG+113,
	CURLOPT_CUSTOMREQUEST = CURLOPTTYPE_OBJECTPOINT+36,
	CURLOPT_LOW_SPEED_LIMIT = CURLOPTTYPE_LONG+19,
	CURLOPT_EGDSOCKET = CURLOPTTYPE_OBJECTPOINT+77,
	CURLOPT_PROXY = CURLOPTTYPE_OBJECTPOINT+4,
	CURLOPT_HTTPHEADER = CURLOPTTYPE_OBJECTPOINT+23,
	CURLOPT_TIMECONDITION = CURLOPTTYPE_LONG+33,
	CURLOPT_SSL_VERIFYSTATUS = CURLOPTTYPE_LONG+232,
	CURLOPT_SSL_CTX_DATA = CURLOPTTYPE_OBJECTPOINT+109,
	CURLOPT_SSLVERSION = CURLOPTTYPE_LONG+32,
	CURLOPT_BUFFERSIZE = CURLOPTTYPE_LONG+98,
	CURLOPT_KRBLEVEL = CURLOPTTYPE_OBJECTPOINT+63,
	CURLOPT_INTERLEAVEDATA = CURLOPTTYPE_OBJECTPOINT+195,
	CURLOPT_KEYPASSWD = CURLOPTTYPE_OBJECTPOINT+26,
	CURLOPT_HTTPGET = CURLOPTTYPE_LONG+80,
	CURLOPT_SSLENGINE_DEFAULT = CURLOPTTYPE_LONG+90,
	CURLOPT_DIRLISTONLY = CURLOPTTYPE_LONG+48,
	CURLOPT_CAINFO = CURLOPTTYPE_OBJECTPOINT+65,
	CURLOPT_READFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+12,
	CURLOPT_NETRC_FILE = CURLOPTTYPE_OBJECTPOINT+118,
	CURLOPT_FAILONERROR = CURLOPTTYPE_LONG+45,
	CURLOPT_SSLENGINE = CURLOPTTYPE_OBJECTPOINT+89,
	CURLOPT_SSLKEYTYPE = CURLOPTTYPE_OBJECTPOINT+88,
	CURLOPT_RTSP_CLIENT_CSEQ = CURLOPTTYPE_LONG+193,
	CURLOPT_CAPATH = CURLOPTTYPE_OBJECTPOINT+97,
	CURLOPT_IGNORE_CONTENT_LENGTH = CURLOPTTYPE_LONG+136,
	CURLOPT_DEBUGFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+94,
	CURLOPT_WRITEFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+11,
	CURLOPT_QUOTE = CURLOPTTYPE_OBJECTPOINT+28,
	CURLOPT_USERPWD = CURLOPTTYPE_OBJECTPOINT+5,
	CURLOPT_UPLOAD = CURLOPTTYPE_LONG+46,
	CURLOPT_TIMEOUT = CURLOPTTYPE_LONG+13,
	CURLOPT_PASSWORD = CURLOPTTYPE_OBJECTPOINT+174,
	CURLOPT_POSTQUOTE = CURLOPTTYPE_OBJECTPOINT+39,
	CURLOPT_DEBUGDATA = CURLOPTTYPE_OBJECTPOINT+95,
	CURLOPT_CONV_FROM_NETWORK_FUNCTION = CURLOPTTYPE_FUNCTIONPOINT+142,
	CURLOPT_UNRESTRICTED_AUTH = CURLOPTTYPE_LONG+105,
	CURLOPT_HTTPAUTH = CURLOPTTYPE_LONG+107,
	CURLOPT_INFILESIZE_LARGE = CURLOPTTYPE_OFF_T+115,
	CURLOPT_CRLF = CURLOPTTYPE_LONG+27,
	CURLOPT_PROXYTYPE = CURLOPTTYPE_LONG+101,
	CURLOPT_INFILESIZE = CURLOPTTYPE_LONG+14,
	CURLOPT_HTTP_VERSION = CURLOPTTYPE_LONG+84,
	CURLOPT_CONV_FROM_UTF8_FUNCTION = CURLOPTTYPE_FUNCTIONPOINT+144,
	CURLOPT_CONNECT_ONLY = CURLOPTTYPE_LONG+141,
	CURLOPT_WRITEDATA = CURLOPTTYPE_OBJECTPOINT+1,
	CURLOPT_UNIX_SOCKET_PATH = CURLOPTTYPE_OBJECTPOINT+231,
	CURLOPT_IOCTLFUNCTION = CURLOPTTYPE_FUNCTIONPOINT+130,
	CURLOPT_SERVICE_NAME = CURLOPTTYPE_OBJECTPOINT+236,
	CURLOPT_MIMEPOST = CURLOPTTYPE_OBJECTPOINT+269
} CURLoption;

typedef void CURL, curl_mime, curl_mimepart;
typedef size_t (*curl_write_callback)(char *,
                                      size_t,
                                      size_t,
                                      void *);

struct mycurlbuffer {
	size_t size, used;
	char *buf;
};

void *malloc(size_t);
void *realloc(void *, size_t);
void *memset(void *, int, size_t);
void free(void *);

CURL *curl_easy_init(void);
CURLcode curl_easy_setopt(CURL *, CURLoption, ...);
CURLcode curl_easy_perform(CURL *);
void curl_easy_cleanup(CURL *);
const char *curl_easy_strerror(CURLcode);

curl_mime *curl_mime_init(CURL *);
curl_mimepart *curl_mime_addpart(CURL *);
CURLcode curl_mime_name(CURL *, const char *);
CURLcode curl_mime_filedata(CURL *, const char *);
void curl_mime_free(CURL *);
